### ISSUE TITLE
[HT-ST5000 soundbar] On/Off not updated in Home.app

### ISSUE THREAD

**Issue by 6MH89F3j** [torandreroland/homebridge-sony-audio-control#10]
First of all, thank you for your work on this plugin. It is a game changer for me, as it allows me to keep my soundbar remote in a drawer! :-)

I recently updated to v2.4.1, and overall it appears to be working just as well as v2.3.0

One issue that I figured I would raise now is that the On/Off tile in the Home.app rarely updates. Not sure if I have something misconfigured or if it's a limitation of how the soundbar goes into standby, etc. Let me know if there are any logs I could provide to help triage the issue.

This is not an urgent issue for me, since HDMI-CEC handles turning on/off the soundbar via the TV. But figured I would bring it up just in case.

To be clear, this is not new to v2.4.1

**Comment by torandreroland** [comment]
This is when changing power on the device / using the remote? I.e. Home.app ability to reflect what is happening on the device, without the Home.app being the source of the change?

**Comment by 6MH89F3j** [comment]
After resetting a lot of stuff (my network, Hoobs) and re-installing, this started working correctly. Everything was actually working great for a while, and then today I updated a separate plugin on my Hoobs, and now I keep getting "getVolume() failed: Cannot read property 'volume' of undefined". I will file a separate bug for it if I can't get things figured out.
