### ISSUE TITLE
[HT-ST5000 soundbar] Volume control issues

### ISSUE THREAD

**Issue by 6MH89F3j** [torandreroland/homebridge-sony-audio-control#11]
I noticed the Volume control (via light bulb) in Home.app is not always updating.

Also, if I try to add a volume control limit in the plugin configuration (from a Hoobs setup), it puts the plugin into a bad state and the soundbar stops responding in the Home.app. The console shows an issue with being able to call getVolume ()

I had to restore from a Hoobs backup to get the plugin back into a good state.

I dont think this is necessarily new to v2.4.1

Also, it is not a huge deal to me, since I use the HDMI-CEC anything to control the volume from my Apple TV and normal TV remote. But wanted to bring to your attention.

**Comment by torandreroland** [comment]
Could you post the logs related to getVolume?

**Comment by 6MH89F3j** [comment]
I am having other issues with the plugin at the moment. Once I get those resolved I will re-test this and file a new bug if I still see the issue.
