### ISSUE TITLE
How do I get the port number for my device?

### ISSUE THREAD

**Issue by 6MH89F3j** [torandreroland/homebridge-sony-audio-control#12]
I am leaving the port field blank and letting it use the default of 10000. It seems to work most of the time, but some times I do see issues where the web socket client can't connect.

How do I get the port number of my device? In this case, my device is a HT-ST5000 soundbar.

This isn't a bug, I am just trying to understand better.

**Comment by torandreroland** [comment]
Just stick with 10000 unless your positive about having to use another port number:-)

The network on my device is a bit unreliable which means it drops websocket connection from time to time (it reconnects automatically when the device is available on the network again).

Do you see the following log message when starting the plugin "WebSocket client connected on endpoint ws://{your ip}:10000/sony/avContent" and "WebSocket client connected on endpoint ws://{your ip}:10000/sony/audio"? If so, then that means the port is correct...

**Comment by 6MH89F3j** [comment]
Yep, that's what I see. Thanks!
