### ISSUE TITLE
API Link Dead

### ISSUE THREAD

**Issue by niallplatts** [torandreroland/homebridge-sony-audio-control#23]
API Link to Sony's documentation has broken. Here is the updated link for the API Documentation from Sony's website.
https://developer.sony.com/audio-control-api/guides-and-examples/how-to-use-the-device-resource-uri/

**Comment by torandreroland** [comment]
Thank you for pointing this out. I update the code here in github (see commit [5fa0add]( https://github.com/torandreroland/homebridge-sony-audio-control/commit/5fa0add83be789384e17daf937256aed57323eb3)).

I won't push a new version based on this small, isolated change though.
