### ISSUE TITLE
Needs a port number option

### ISSUE THREAD

**Issue by UiharuKazari2008** [torandreroland/homebridge-sony-audio-control#4]
I have a Sony Hear.Go HiFi speaker and it uses http://192.168.100.8:54480/sony NOT port 10000 and it cant connect

**Comment by torandreroland** [comment]
Are you sure this speaker supports the Sony audio control api?

**Comment by UiharuKazari2008** [comment]
Yes, I have made a modified version of this repo and it works fine with no issues. Just a few API commands are different and the port number is different 
https://code.acr.moe/kazari/homebridge-sony-audio-control

**Comment by torandreroland** [comment]
This should be supported now in version 2.41. Closing issue.
