### ISSUE TITLE
SoundFields specific values

### ISSUE THREAD

**Issue by hylkefaber** [torandreroland/homebridge-sony-audio-control#5]
I cannot seem to find the specific values that are allowed in the soundFields[] array. There's no mention of it in the official API

**Comment by torandreroland** [comment]
You have to make an array with objects consisting of name and value, e.g.:

[
    {
        "name": "Stereo Mode",
        "value": "2chStereo"
    },
    {
        "name": "Surround Mode",
        "value": "dolbySurround"
    }
]

Valid values on a STR-DN1080 looks to be: 2chStereo, multiChStereo, direct, audioFormatDecoding, dolbySurround, neuralX, frontSurround and audioEnhancer. Name can be whatever you prefer in HomeKit or when talking to Siri.
