### ISSUE TITLE
[feature] custome setCharacteristics on config file

### ISSUE THREAD

**Issue by carlosgamezvillegas** [torandreroland/homebridge-sony-audio-control#7]
Hello guys, thank you so much for this plug in, I love it having it in my Home. 

I have one request regarding the characteristics set on the plug-in. Could you add “Model”, “Manufacturer” and “Serial Number”  to the settings so we can change them manually? Right now when you try to see the details of the vacuum in HomeKit it says “default” for model and a long serial number. I have tried to change the .setCharacteristics on the js but it doesn’t seem to work. I have done that with other plugins but I can’t make this one work. I think this will help to make it look more like a native HomeKit device .

Thanks,

**Comment by torandreroland** [comment]
Added configurable manufacturer, model and serial in release 2.4.3.
