### ISSUE TITLE
Unable to install v2.4.0

### ISSUE THREAD

**Issue by 6MH89F3j** [torandreroland/homebridge-sony-audio-control#8]
I’m trying to update to the latest version of the plugin on my Hoobs setup, however it is failing to install the plugin.

I’m using your plugin with a Sony HT-ST5000 sound bar. I mainly just use it to switch the sound field settings, and v2.3.0 works really well for that (thanks!). The on/off doesnt work well. So, I wanted to try your latest plugin, but haven’t been able to get it to install yet.

Let me know if you need any other info, or if I can help debug further.

11/28/2020, 12:42:25 AM npm
11/28/2020, 12:42:25 AM  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/term-size/node_modules/.bin/which
npm ERR!
11/28/2020, 12:42:25 AM  Refusing to delete /home/hoobs/.hoobs/node_modules/term-size/node_modules/.bin/which: is outside /home/hoobs/.hoobs/node_modules/term-size/node_modules/which and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/term-size/node_modules/.bin/which
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
11/28/2020, 12:42:25 AM 
11/28/2020, 12:42:25 AM npm
11/28/2020, 12:42:25 AM  ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-11-28T08_42_25_666Z-debug.log

And here is the content of the complete log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--no-audit',
1 verbose cli   '--progress=true',
1 verbose cli   'homebridge-sony-audio-control@2.4.0'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session c3c80fe5667833c0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-sony-audio-control 400
9ms (from cache)
8 silly pacote version manifest for homebridge-sony-audio-control@2.4.0 fetched  
in 463ms
9 timing stage:loadCurrentTree Completed in 13379ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 173ms
"2020-11-28T08_42_25_666Z-debug.log" 5856 lines, 898964 characters

**Comment by torandreroland** [comment]
I don't think is an issue with the plugin but with the Hoobs install or some corruption in the npm registry. Could you have a look at https://stackoverflow.com/questions/46541371/npm-err-refusing-to-delete-code-eexist/46541654 ?

**Comment by 6MH89F3j** [comment]
Thanks for the reply. I did some digging and ended having to remove the following folders on my system:
/home/hoobs/.hoobs/node_modules/npm
/home/hoobs/.hoobs/node_modules/np

And then it was able to install properly. Thanks for the tip.

Overall, the updated plugin (v2.4.1) seems to be running the same as before. I will open a couple bugs, that I believe existed before updating.

You can close this issue out.

**Comment by torandreroland** [comment]
Thanks for the update. Closing this issue.
